/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}

rootProject.name = "s2-geometry-parent"
include(":s2-geometry-library")
include(":s2-geometry-benchmarks")
include(":s2-geometry-tests")
project(":s2-geometry-library").projectDir = file("library")
project(":s2-geometry-benchmarks").projectDir = file("benchmarks")
project(":s2-geometry-tests").projectDir = file("tests")
