/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":s2-geometry-library"))
    api(libs.com.google.guava.guava)
    api(libs.it.unimi.dsi.fastutil)
    testImplementation(libs.com.google.truth.truth)
    testImplementation(libs.junit.junit)
}

description = "S2 Geometry Library Tests"
